import type { Product } from "./types";

export const newProducts: Product[] = [
  {
    slug: "punk-rock-battle-jacket",
    name: "Punk Rock Battle Jacket",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Turn heads and own the pit with our premium, heavily customized leather biker jacket. Inspired by decades of underground rock culture, this isn't just outerwear—it’s a wearable manifesto.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/punk-rock-battle-jacket/1.jpeg",
      "/products/punk-rock-battle-jacket/2.jpeg",
      "/products/punk-rock-battle-jacket/3.jpeg",
      "/products/punk-rock-battle-jacket/4.jpeg"
    ],
  },
  {
    slug: "red-rock-metal-battle-jacket",
    name: "Red Rock & Metal Battle Jacket",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Break away from the traditional black leather look and command attention with this custom, premium red leather biker jacket.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/red-rock-metal-battle-jacket/1.jpeg",
      "/products/red-rock-metal-battle-jacket/2.jpeg",
      "/products/red-rock-metal-battle-jacket/3.jpeg",
      "/products/red-rock-metal-battle-jacket/4.jpeg"
    ],
  },
  {
    slug: "white-gold-battle-jacket",
    name: "White & Gold Battle Jacket",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Step into the spotlight with an elite twist on classic punk and rock aesthetics.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/white-gold-battle-jacket/1.jpeg",
      "/products/white-gold-battle-jacket/2.jpeg",
      "/products/white-gold-battle-jacket/3.jpeg",
      "/products/white-gold-battle-jacket/4.jpeg"
    ],
  },
  {
    slug: "royal-blue-hardcore-battle-jacket",
    name: "Royal Blue Hardcore Battle Jacket",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Ditch the ordinary and make a massive visual statement with this premium, custom-designed royal blue leather motorcycle jacket.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/royal-blue-hardcore-battle-jacket/1.jpeg",
      "/products/royal-blue-hardcore-battle-jacket/2.jpeg",
      "/products/royal-blue-hardcore-battle-jacket/3.jpeg",
      "/products/royal-blue-hardcore-battle-jacket/4.jpeg"
    ],
  },
  {
    slug: "dark-green-battle-jacket",
    name: "Dark Green Battle Jacket",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Step away from traditional black leather and embrace a rugged, custom aesthetic with this premium dark green leather biker jacket.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/dark-green-battle-jacket/1.jpeg",
      "/products/dark-green-battle-jacket/2.jpeg",
      "/products/dark-green-battle-jacket/3.jpeg",
      "/products/dark-green-battle-jacket/4.jpeg"
    ],
  },
  {
    slug: "custom-distressed-brown-battle-jacket",
    name: "Custom Distressed Brown Battle Jacket",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Embrace the raw, unyielding spirit of the open highway with this premium dark brown leather biker jacket.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/custom-distressed-brown-battle-jacket/1.jpeg",
      "/products/custom-distressed-brown-battle-jacket/2.jpeg",
      "/products/custom-distressed-brown-battle-jacket/3.jpeg",
      "/products/custom-distressed-brown-battle-jacket/4.jpeg"
    ],
  },
  {
    slug: "yellow-punk-rock-battle-jacket",
    name: "Yellow Punk Rock Battle Jacket",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Shatter the mold of conventional streetwear and unleash pure anarchy with this custom, premium electric yellow leather biker jacket.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/yellow-punk-rock-battle-jacket/1.jpeg",
      "/products/yellow-punk-rock-battle-jacket/2.jpeg",
      "/products/yellow-punk-rock-battle-jacket/3.jpeg",
      "/products/yellow-punk-rock-battle-jacket/4.jpeg"
    ],
  },
  {
    slug: "gothic-punk-battle-jacket",
    name: "Gothic Punk Battle Jacket",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Step into the shadows and claim your crown with this custom, premium deep purple leather biker jacket.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/gothic-punk-battle-jacket/1.jpeg",
      "/products/gothic-punk-battle-jacket/2.jpeg",
      "/products/gothic-punk-battle-jacket/3.jpeg",
      "/products/gothic-punk-battle-jacket/4.jpeg"
    ],
  },
  {
    slug: "orange-spiked-racing-jacket",
    name: "Orange Spiked Racing Jacket",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Ignite your style and leave the competition in the dust with this premium, custom-designed vibrant orange leather racing jacket.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/orange-spiked-racing-jacket/1.jpeg",
      "/products/orange-spiked-racing-jacket/2.jpeg",
      "/products/orange-spiked-racing-jacket/3.jpeg",
      "/products/orange-spiked-racing-jacket/4.jpeg"
    ],
  },
  {
    slug: "custom-max-studded-battle",
    name: "Custom Max-Studded Battle",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Command absolute authority in the pit, on the stage, or on the open road with our most heavily customized leather masterpiece yet.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/custom-max-studded-battle/1.jpeg",
      "/products/custom-max-studded-battle/2.jpeg",
      "/products/custom-max-studded-battle/3.jpeg",
      "/products/custom-max-studded-battle/4.jpeg"
    ],
  },
  {
    slug: "vintage-outlaw-battle-jacket",
    name: "Vintage Outlaw Battle Jacket",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Channel the raw, unyielding history of the open highway with a masterpiece designed for the true road warrior.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/vintage-outlaw-battle-jacket/1.jpeg",
      "/products/vintage-outlaw-battle-jacket/2.jpeg",
      "/products/vintage-outlaw-battle-jacket/3.jpeg",
      "/products/vintage-outlaw-battle-jacket/4.jpeg"
    ],
  },
  {
    slug: "forest-green-battle-jacket",
    name: "Forest Green Battle Jacket",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Break away from conventional styling and venture into a realm of dark, organic rebellion.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/forest-green-battle-jacket/1.jpeg",
      "/products/forest-green-battle-jacket/2.jpeg",
      "/products/forest-green-battle-jacket/3.jpeg",
      "/products/forest-green-battle-jacket/4.jpeg"
    ],
  },
  {
    slug: "crystal-studded-leather-jacket",
    name: "Crystal Studded Leather Jacket",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Elevate your alternative wardrobe with a sophisticated, high-end spin on the classic punk-rock aesthetic.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/crystal-studded-leather-jacket/1.jpeg",
      "/products/crystal-studded-leather-jacket/2.jpeg",
      "/products/crystal-studded-leather-jacket/3.jpeg",
      "/products/crystal-studded-leather-jacket/4.jpeg"
    ],
  },
  {
    slug: "gothic-crown-burgundy-jacket",
    name: "Gothic Crown Burgundy Jacket",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Infuse your wardrobe with an air of dark royalty and raw rebellion.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/gothic-crown-burgundy-jacket/1.jpeg",
      "/products/gothic-crown-burgundy-jacket/2.jpeg",
      "/products/gothic-crown-burgundy-jacket/3.jpeg",
      "/products/gothic-crown-burgundy-jacket/4.jpeg"
    ],
  },
  {
    slug: "white-spiked-armor-battle-jacket",
    name: "White Spiked Armor Battle Jacket",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Make an unforgettable visual statement and command center stage with this premium, custom-designed white leather biker jacket.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/white-spiked-armor-battle-jacket/1.jpeg",
      "/products/white-spiked-armor-battle-jacket/2.jpeg",
      "/products/white-spiked-armor-battle-jacket/3.jpeg",
      "/products/white-spiked-armor-battle-jacket/4.jpeg"
    ],
  },
  {
    slug: "royal-blue-armor-battle-jacket",
    name: "Royal Blue Armor Battle Jacket",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Command the crowd and shatter the mold of traditional streetwear with this premium, custom-designed royal blue leather biker jacket.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/royal-blue-armor-battle-jacket/1.jpeg",
      "/products/royal-blue-armor-battle-jacket/2.jpeg",
      "/products/royal-blue-armor-battle-jacket/3.jpeg",
      "/products/royal-blue-armor-battle-jacket/4.jpeg"
    ],
  },
  {
    slug: "handcrafted-aztec-battle-jacket",
    name: "Handcrafted Aztec Battle Jacket",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Forge your own path with a piece that perfectly blends ancestral geometric patterns with raw, aggressive motorcycle culture.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/handcrafted-aztec-battle-jacket/1.jpeg",
      "/products/handcrafted-aztec-battle-jacket/2.jpeg",
      "/products/handcrafted-aztec-battle-jacket/3.jpeg",
      "/products/handcrafted-aztec-battle-jacket/4.jpeg"
    ],
  },
  {
    slug: "intricate-diamond-lattice-battle-armor",
    name: "Intricate Diamond Lattice Battle Armor",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Redefine alternative luxury and step into an elite realm of dark glamour.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/intricate-diamond-lattice-battle-armor/1.jpeg",
      "/products/intricate-diamond-lattice-battle-armor/2.jpeg",
      "/products/intricate-diamond-lattice-battle-armor/3.jpeg",
      "/products/intricate-diamond-lattice-battle-armor/4.jpeg"
    ],
  },
  {
    slug: "botanical-armor-battle-jacket",
    name: "Botanical Armor Battle Jacket",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Venture into a realm of dark, organic rebellion and shatter conventional style boundaries.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/botanical-armor-battle-jacket/1.jpeg",
      "/products/botanical-armor-battle-jacket/2.jpeg",
      "/products/botanical-armor-battle-jacket/3.jpeg",
      "/products/botanical-armor-battle-jacket/4.jpeg"
    ],
  },
  {
    slug: "custom-weathered-brown-compass-battle-jacket",
    name: "Custom Weathered Brown Compass Battle Jacket",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Embody the spirit of a legendary wanderer and chart your own path with this custom, premium distressed brown leather biker jacket.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/custom-weathered-brown-compass-battle-jacket/1.jpeg",
      "/products/custom-weathered-brown-compass-battle-jacket/2.jpeg",
      "/products/custom-weathered-brown-compass-battle-jacket/3.jpeg",
      "/products/custom-weathered-brown-compass-battle-jacket/4.jpeg"
    ],
  },
  {
    slug: "celestial-constellation-battle-jacket",
    name: "Celestial Constellation Battle Jacket",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Align your style with the stars and break away from conventional streetwear.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/celestial-constellation-battle-jacket/1.jpeg",
      "/products/celestial-constellation-battle-jacket/2.jpeg",
      "/products/celestial-constellation-battle-jacket/3.jpeg",
      "/products/celestial-constellation-battle-jacket/4.jpeg"
    ],
  },
  {
    slug: "gold-armored-white-battle-jacket",
    name: "Gold-Armored White Battle Jacket",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Ascend to the absolute peak of alternative luxury and command center stage with a visual statement that cannot be ignored.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/gold-armored-white-battle-jacket/1.jpeg",
      "/products/gold-armored-white-battle-jacket/2.jpeg",
      "/products/gold-armored-white-battle-jacket/3.jpeg",
      "/products/gold-armored-white-battle-jacket/4.jpeg"
    ],
  },
  {
    slug: "gothic-cathedral-burgundy-armor",
    name: "Gothic Cathedral Burgundy Armor",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Step into a realm of dark romance, sacred geometry, and raw rebellion with a wearable masterpiece that transcends ordinary fashion.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/gothic-cathedral-burgundy-armor/1.jpeg",
      "/products/gothic-cathedral-burgundy-armor/2.jpeg",
      "/products/gothic-cathedral-burgundy-armor/3.jpeg",
      "/products/gothic-cathedral-burgundy-armor/4.jpeg"
    ],
  },
  {
    slug: "crimson-studded-flame-battle-jacket",
    name: "Crimson Studded Flame Battle Jacket",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Ignite your alternative style and shatter conventional design boundaries.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/crimson-studded-flame-battle-jacket/1.jpeg",
      "/products/crimson-studded-flame-battle-jacket/2.jpeg",
      "/products/crimson-studded-flame-battle-jacket/3.jpeg",
      "/products/crimson-studded-flame-battle-jacket/4.jpeg"
    ],
  },
  {
    slug: "bronze-winged-battle-jacket",
    name: "Bronze Winged Battle Jacket",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Forge a legendary path and shatter the boundaries of conventional style.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/bronze-winged-battle-jacket/1.jpeg",
      "/products/bronze-winged-battle-jacket/2.jpeg",
      "/products/bronze-winged-battle-jacket/3.jpeg",
      "/products/bronze-winged-battle-jacket/4.jpeg"
    ],
  },
  {
    slug: "teal-green-studded-battle-jacket",
    name: "Teal Green Studded Battle Jacket",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Command the crowd and shatter the mold of traditional alternative streetwear with this premium, custom-designed teal green leather biker jacket.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/teal-green-studded-battle-jacket/1.jpeg",
      "/products/teal-green-studded-battle-jacket/2.jpeg",
      "/products/teal-green-studded-battle-jacket/3.jpeg",
      "/products/teal-green-studded-battle-jacket/4.jpeg"
    ],
  },
  {
    slug: "occult-purple-battle-jacket",
    name: "Occult Purple Battle Jacket",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Channel an aura of dark mysticism and unyielding rebellion with this premium, custom-designed purple leather biker jacket.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/occult-purple-battle-jacket/1.jpeg",
      "/products/occult-purple-battle-jacket/2.jpeg",
      "/products/occult-purple-battle-jacket/3.jpeg",
      "/products/occult-purple-battle-jacket/4.jpeg"
    ],
  },
  {
    slug: "studded-lightning-bolt-battle-jacket",
    name: "Studded Lightning Bolt Battle Jacket",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Electrify your alternative wardrobe and send a shockwave through the status quo.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/studded-lightning-bolt-battle-jacket/1.jpeg",
      "/products/studded-lightning-bolt-battle-jacket/2.jpeg",
      "/products/studded-lightning-bolt-battle-jacket/3.jpeg",
      "/products/studded-lightning-bolt-battle-jacket/4.jpeg"
    ],
  },
  {
    slug: "interactive-cyberpunk-battle-armor",
    name: "Interactive Cyberpunk Battle Armor",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Step directly into the future and claim your place in the neo-metropolis.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/interactive-cyberpunk-battle-armor/1.jpeg",
      "/products/interactive-cyberpunk-battle-armor/2.jpeg",
      "/products/interactive-cyberpunk-battle-armor/3.jpeg",
      "/products/interactive-cyberpunk-battle-armor/4.jpeg"
    ],
  },
  {
    slug: "intricate-geometric-studded-battle-armor",
    name: "Intricate Geometric Studded Battle Armor",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Redefine alternative luxury and step into an elite realm of dark glamour.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/intricate-geometric-studded-battle-armor/1.jpeg",
      "/products/intricate-geometric-studded-battle-armor/2.jpeg",
      "/products/intricate-geometric-studded-battle-armor/3.jpeg",
      "/products/intricate-geometric-studded-battle-armor/4.jpeg"
    ],
  },
  {
    slug: "blood-red-skull-crossbones-battle-jacket",
    name: "Blood Red Skull & Crossbones Battle Jacket",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Ignite your alternative style and shatter the mold of conventional streetwear.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/blood-red-skull-crossbones-battle-jacket/1.jpeg",
      "/products/blood-red-skull-crossbones-battle-jacket/2.jpeg",
      "/products/blood-red-skull-crossbones-battle-jacket/3.jpeg",
      "/products/blood-red-skull-crossbones-battle-jacket/4.jpeg"
    ],
  },
  {
    slug: "gold-armored-burgundy-battle-jacket",
    name: "Gold-Armored Burgundy Battle Jacket",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Ascend to the peak of alternative luxury and command absolute attention with a bold visual masterpiece.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/gold-armored-burgundy-battle-jacket/1.jpeg",
      "/products/gold-armored-burgundy-battle-jacket/2.jpeg",
      "/products/gold-armored-burgundy-battle-jacket/3.jpeg"
    ],
  },
  {
    slug: "distressed-star-studded-battle-jacket",
    name: "Distressed Star Studded Battle Jacket",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Embody the spirit of vintage Americana, rugged exploration, and raw rock-and-roll heritage.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/distressed-star-studded-battle-jacket/1.jpeg",
      "/products/distressed-star-studded-battle-jacket/2.jpeg",
      "/products/distressed-star-studded-battle-jacket/3.jpeg",
      "/products/distressed-star-studded-battle-jacket/4.jpeg"
    ],
  },
  {
    slug: "brass-armored-espresso-battle-jacket",
    name: "Brass-Armored Espresso Battle Jacket",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Forge an undeniable statement of rugged rebellion and timeless rock-and-roll heritage.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/brass-armored-espresso-battle-jacket/1.jpeg",
      "/products/brass-armored-espresso-battle-jacket/2.jpeg",
      "/products/brass-armored-espresso-battle-jacket/3.jpeg",
      "/products/brass-armored-espresso-battle-jacket/4.jpeg"
    ],
  },
  {
    slug: "3d-skull-armored-battle-jacket",
    name: "3D Skull-Armored Battle Jacket",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Unleash an uncompromising statement of dark rebellion, heavy-metal heritage, and raw road-worn grit.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/3d-skull-armored-battle-jacket/1.jpeg",
      "/products/3d-skull-armored-battle-jacket/2.jpeg",
      "/products/3d-skull-armored-battle-jacket/3.jpeg",
      "/products/3d-skull-armored-battle-jacket/4.jpeg"
    ],
  },
  {
    slug: "high-shine-spiked-flame-jacket",
    name: "High-Shine Spiked Flame Jacket",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Ignite your alternative style and shatter conventional design boundaries with an unmistakable visual statement.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/high-shine-spiked-flame-jacket/1.jpeg",
      "/products/high-shine-spiked-flame-jacket/2.jpeg",
      "/products/high-shine-spiked-flame-jacket/3.jpeg",
      "/products/high-shine-spiked-flame-jacket/4.jpeg"
    ],
  },
  {
    slug: "vintage-outlaw-mc-studded-cruiser-jacket",
    name: "Vintage Outlaw M.C. Studded Cruiser Jacket",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Embody the raw, unyielding heritage of classic American motorcycle culture and traditional rock-and-roll rebellion.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/vintage-outlaw-mc-studded-cruiser-jacket/1.jpeg",
      "/products/vintage-outlaw-mc-studded-cruiser-jacket/2.jpeg",
      "/products/vintage-outlaw-mc-studded-cruiser-jacket/3.jpeg",
      "/products/vintage-outlaw-mc-studded-cruiser-jacket/4.jpeg"
    ],
  },
  {
    slug: "full-armored-black-battle-jacket",
    name: "Full-Armored Black Battle Jacket",
    gender: "Men",
    category: "Jackets",
    price: 349,
    description: "Command the crowd and unleash an uncompromising statement of dark rebellion.",
    kicker: "Men's Battle Jackets",
    details: [
      "Premium top-grain cowhide leather",
      "Hand-set chrome spikes and studs",
      "Asymmetrical YKK front zipper",
      "Adjustable waist belt",
    ],
    materials: "100% Genuine Top-Grain Cowhide Leather. Condition every 6 months with a neutral leather balm.",
    shipping: "Ships within 3 business days. Tracked express delivery, 5–9 days internationally.",
    sizes: ["S", "M", "L", "XL"],
    relatedProducts: [],
    images: [
      "/products/full-armored-black-battle-jacket/1.jpeg",
      "/products/full-armored-black-battle-jacket/2.jpeg",
      "/products/full-armored-black-battle-jacket/3.jpeg",
      "/products/full-armored-black-battle-jacket/4.jpeg"
    ],
  },
];
